### ISSUE TITLE
Changes to NFT.sol

### ISSUE THREAD

**Issue by AlphaVS-76** [developerasun/pawcon#117]
## Problem In: 

- [NFT.sol](https://github.com/developerasun/pawcon/blob/main/blockchain/contracts/NFT.sol) file.

## Current Problems:

- The Import statements are giving an error when run on remix IDE without the specific folders mentioned.

## Suggested Changes: 

- Changing the import statement from directory path to the actual repo in GitHub.

## Assignees:

- I would like to be assigned this issue.

**Comment by developerasun** [comment]
Previous codes in NFT.sol is moved and split to other contracts files such as 

- [CuriousPawoneer.sol](https://github.com/developerasun/pawcon/blob/main/blockchain/contracts/token/ERC721/CuriousPawoneer.sol)
- [Churu.sol](https://github.com/developerasun/pawcon/blob/main/blockchain/contracts/token/ERC20/Churu.sol)

The NFT.sol will be deleted or refactored later. 

As to the import error, please see [this issue](https://github.com/juanfranblanco/vscode-solidity/issues/178) first :) 

If the the import path is fixed like below, 

```solidity 
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
```

the import error will be gone in Remix but still exists in VS code even if the setting is done as suggested in the issue, which is the editor I'm working with now - so currently just imported it from node_modules right away for convenience. 

Please do your research and make a pull request :)

**Comment by developerasun** [comment]
I will add issue template later so that open source contributors can use!

**Comment by AlphaVS-76** [comment]
> I will add issue template later so that open source contributors can use!

I can help with that as well!

**Comment by developerasun** [comment]
> > I will add issue template later so that open source contributors can use!
> 
> I can help with that as well!

Sweet! :) I think you can develop the current format you are using, which looks good already
