### ISSUE TITLE
[Open Source Report] Pull Request Template Draft

### ISSUE THREAD

**Issue by AlphaVS-76** [developerasun/pawcon#147]
## Closes/Successor of
<#[ISSUE NO.]>

## Changes Proposed (Descriptive)
<[Changes/solutions to be made]>

## Checklist (Check all the applicable boxes)
- [ ] This PR does not contain plagiarized content.
- [ ] My change requires changes to the documentation.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.

## Assignee (Optional)
<[The person who wants to be assigned this issue]>

**Comment by developerasun** [comment]
Looks very promising! Will definitely reflect this into templates. 

Besides this, I'm working on smart contract test codes and felt like maybe you want to be involved?  I remember that you are interested in building contracts :)

You can play around a deployed contract in etherscan(ERC20 Churu.sol, ropsten network. ERC721 Curious pawoneer not deployed yet.)

- [Churu](https://ropsten.etherscan.io/address/0x0f4d7069B9a58699D7c369F9ac97777fBDe4e8e4#code)

Let me know what you think!

**Comment by AlphaVS-76** [comment]
Sure, I'll give it a go!

**Comment by developerasun** [comment]
Should integrate the suggestion, following below docs from github. 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by developerasun** [comment]
## integration

- the template reflected in commit : 9229f06102347431f862a57f22b967a641ef4238

## result 

![image](https://user-images.githubusercontent.com/83855174/159462646-20ae610a-d31f-44cd-93c8-0501b1380622.png)
