### ISSUE TITLE
React/TS : Argument of type '() => Promise<void>' is not assignable to parameter of type 'EffectCallback'

### ISSUE THREAD

**Issue by developerasun** [developerasun/pawcon#48]
# issue : can't make useEffect callback async but worked in React/JS

## in React/TScodes, 
![react-ts-async-in-useEffect](https://user-images.githubusercontent.com/83855174/148534906-355bc917-d6a9-4355-b79f-3f5595cff26d.png)

**Comment by developerasun** [comment]
Read below. 
https://stackoverflow.com/questions/57238928/react-typescript-16-8-how-to-make-useeffect-async

**Comment by developerasun** [comment]
## solution : do not make useEffect async function but use async functions IN useEffect.

**Comment by miskhill** [comment]
I had this just due to the callback and useState not being in the component page function.

**Comment by developerasun** [comment]
> I had this just due to the callback and useState not being in the component page function. 

Can you provide the codes ? :) I'd like to see what it went wrong in your case!!

**Comment by QuangAn1312** [comment]
nice

**Comment by developerasun** [comment]
> nice

My pleasure! :)
