### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by AlphaVS-76** [developerasun/pawcon#91]
Changes:
- The headers in the READM.md file are somewhat varied
- Some texts are in bold format, which looks kind of inconsistent
- Adding some more links for connecting with you in the [Contact](https://github.com/developerasun/pawcon#contact) section such as (Twitter, Instagram, Linkedin, etc)

Assignee:
- It would be great if I could be assigned this issue

**Comment by developerasun** [comment]
Thanks for the suggestion and contribution :) below I attached the contact info so please feel free to make changes and do a pull request.

- [Instagram](https://www.instagram.com/designerasun/)
- [Linkedin](https://www.linkedin.com/in/jakesung/)

**Comment by developerasun** [comment]
The pull request have been reviewed and changes merged to main branch! 

![contributors](https://user-images.githubusercontent.com/83855174/151787867-19f9ce50-75d6-457c-b482-91481d36dec5.png)

Later, I will be working on Solidity for NFT contract so it will be great if you want to join in that :)

**Comment by AlphaVS-76** [comment]
I would love to be a part of it! I'm also actively learning Solidity apart from my usual studies!
